In [1]:
#1-dimensional array
import numpy as np
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [2]:
a.ndim

1

In [3]:
#2-dimensional array
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a1.ndim

2

In [5]:
a.shape

(5,)

In [6]:
a1.shape

(3, 3)

In [7]:
#inserting elements into the array dynamically
a3 = np.array([],dtype="int32")

In [8]:
a3 = np.append(a3,int(input()))
a3

55


array([55])

In [9]:
a3 = np.append(a3,[23,34,45,56,67])
a3

array([55, 23, 34, 45, 56, 67])

In [10]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [11]:
a2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
SLICING:

In [12]:
print(a3[3])

45


In [13]:
print(a2[1,1])

5


In [14]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [15]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [16]:
print(a2[0,0:2])

[1 2]


In [17]:
print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]


In [18]:
for row in a2:
    print(row)


[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [19]:
list1 = [[1,2],[3,4]]
for i in list1:
    print(i)


[1, 2]
[3, 4]


In [20]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [21]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [23]:
#even number
result = (arr1 % 2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [24]:
#displaying only even numbers from the 2-dimensional array
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))#vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [26]:
print(np.hstack((arr1,arr2)))#horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [27]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


In [29]:
#zeros()
z = np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
#ones()
o = np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
#full()
f =np.full((2,2),"IRFAN")
print(f)

[['IRFAN' 'IRFAN']
 ['IRFAN' 'IRFAN']]


In [33]:
#eye()
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [34]:
#linspace() -->create an array linear spacing elements
l = np.linspace(1,10,5)
l


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
#arange(start,stop,step) 
a = np.arange(1,13,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [36]:
#reshape()
a = a.reshape(2,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [37]:
#ravel() -->flattens your array elements
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


In [38]:
#min(),max()
print(a.min())
print(a.max())

1
11


In [39]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [40]:
#Sum()
print(a.sum())#sum of all the elements
print(a.sum(axis=1))#sum of row elements
print(a.sum(axis=0))#sum of colunm elements


36
[ 9 27]
[ 8 12 16]


In [41]:
#sqrt()
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [42]:
#mean()
np.mean(a)

6.0

In [43]:
#median()
np.median(a)

6.0

In [44]:
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)
print(arr1 + arr2)
print(arr2 - arr1)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
import numpy as np
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)


array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [46]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [49]:
a = np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [50]:
#1/(1+1) -->X/(X+1)
result = [X/(X+1) for X in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [51]:
f = np.vectorize(lambda X: X/(X+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])